language: node_js
node_js:
  - "8.0"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
after_success:
  - firebase deploy --token $FIREBASE_TOKEN